name: mimos
description: A way to pay on your phone at restaraunts

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

  rxdart: ^0.21.0
  http: ^0.12.0
  fast_qr_reader_view: ^0.1.5
  intl: ^0.15.8
  web_socket_channel: ^1.0.12
  shared_preferences: ^0.5.2
  sticky_headers: ^0.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.7.2
  
flutter_icons:
  android: "launcher_icon" 
  ios: true
  image_path: "images/launcher-icons/mimos-launcher-icon.png"


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # see https://flutter.io/assets-and-images/#from-packages
  #
  # TODO: resolutions for other devices
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.
  assets:
    - images/mimos_logo.png
    - images/mimos_logo_white.png
    - images/silverware.png
    - images/restaurant.jpg

  # see https://flutter.io/custom-fonts/#from-packages
  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Light.ttf
        - asset: fonts/Montserrat-Regular.ttf
        - asset: fonts/Montserrat-Medium.ttf
        - asset: fonts/Montserrat-SemiBold.ttf
        - asset: fonts/Montserrat-Bold.ttf
